### ISSUE TITLE
Liste der Provider und deren Content erstellen

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/iOSX-App#1]
Auflisten, welcher Provider welche Art von Inhalt zur Verfügung stellt.

**Comment by ghost** [comment]
Erledigt! Abgelegt im IOS../Projektmaterial
Link in der Dokumentation:
https://github.com/EEXCESS/eexcess/wiki/%5B21.09.2015%5D-Request-and-Response-format

**Comment by GvRecum** [comment]
partnerList und protectedPartnerList erstellen
https://github.com/EEXCESS/eexcess/wiki/%5B21.09.2015%5D-Request-and-Response-format#registered-partners-format

**Comment by ghost** [comment]
AYAY!

**Comment by GvRecum** [comment]
heute bis **13:00 Uhr** abschliessen.
