### ISSUE TITLE
Implementieren der Sech-,tag- und filter-class

### ISSUE THREAD

**Issue by apoehlmann** [SECH-Tag-EEXCESS-Browser/iOSX-App#10]
Die Klassen werden Implementiert und getestet. Änderungen würde ich direkt in die Dokumentation eintragen.

**Comment by apoehlmann** [comment]
Die Klassen Implementierung muss nochmal überdacht werden, denn da werden viele Informationen mehrfach abgespeichert.

**Comment by apoehlmann** [comment]
Mein Vorschlag wäre:

``` swift
class SechPage{
private let allTags:[String:SechTag] 

init(allTags:[String:SechTag]){
//....
}
func getTag(key:String)->SechTag;
func getAllTags()->[SechTag]
}
class SechTag{
    let topic:String
    let type:String  // [person, location, organization, misc]
    let isMainTopic:Bool
}
class SechLink:SechTag{
  let sechParent:String
// abspeichern der Ergebnisse der Anfrage
}
class SechSection:SechTag{
   let sechParent:String
}

class SechFilter{
let filterOptions:[String:String]
}
```

**Comment by apoehlmann** [comment]
Mit den Sech-Tags, können wir eine Vererbung aufbauen. Der Sech-Meta ist der Startknoten und die SechSections gehen immer mehr ins Detail und die SechLinks sind die Endknoten.

Bei den Anfragen müssten wir diesen Baum von oben nach unten ab arbeiten. Damit bei Klick auf ein SechLink immer sofort Inhalt vorhanden ist und auf Bedarf können wir gleich ein SechLink anfragen.

**Comment by bmairhoermann** [comment]
Aktuelle Stand des Model ist jetzt:

``` swift
class Sech{
    var id = String()
    var response = String() // Tbd
    var detail = String() // Tbd
    var tags = [String : Tag]() // String is id (link, section, head) and Tag is Tag-Object
    var filters = Filter()
}

class Tag {
    var topic = String()
    var type = String()
    var isMainTopic = false
}

class Filter{
    var mediaType = String()
    var provider = String()
    var licence = String()
}

```

**Comment by GvRecum** [comment]
sech -> seach -> auf search anpasen

**Comment by bmairhoermann** [comment]
In der Regex wurden die Analyse der Website auf search-head, search-section, search-link angepasst. Die Javascriptdatei wurde ebenfalls angepasst.

**Comment by GvRecum** [comment]
in doku integrieren
