### ISSUE TITLE
Struktur überarbeiten

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/iOSX-App#14]
Ordnung reinbringen.
in Absprache mit @apoehlmann und @lmoedl

**Comment by apoehlmann** [comment]
Können wir uns dann morgen oder übermorgen treffen -> Sonst können wir nicht beginnen

**Comment by GvRecum** [comment]
Wie habt Ihr am Wochenende Zeit?

**Comment by apoehlmann** [comment]
Schaut euch mal die Änderungen an

**Comment by GvRecum** [comment]
Struktur verworfen und in Passau erneuert.
