### ISSUE TITLE
Ranking besprechen

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/iOSX-App#16]
Bitte Ranking Stand besprechen mit @GvRecum

**Comment by GvRecum** [comment]
Endstand bitte besprechen.

**Comment by GvRecum** [comment]
Heute oder morgen!

**Comment by lmoedl** [comment]
Können wir morgen machen

Gottfried von Recum notifications@github.com schrieb am Mo., 21. Dez.
2015 12:20:

**Comment by lmoedl** [comment]
Die endgültige Dokumentation folgt in den Ferien

Lothar Mödl lothar.moedl@googlemail.com schrieb am Mo., 21. Dez. 2015
12:46:

**Comment by GvRecum** [comment]
Sonntag oder Montag treffen

**Comment by lmoedl** [comment]
Wozu müssen wir uns denn deswegen treffen?
