### ISSUE TITLE
Ranking visualisieren

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/iOSX-App#17]
Wenn das Ranking implementiert wird bitte visualisieren.
in Absprache mit @lmoedl

**Comment by lmoedl** [comment]
Das steht Sinn alles in der Doku

Gottfried von Recum notifications@github.com schrieb am Mi., 2. Dez. 2015
11:07:

**Comment by lmoedl** [comment]
*schon

Lothar Mödl lothar.moedl@googlemail.com schrieb am Do., 3. Dez. 2015
06:52:

**Comment by GvRecum** [comment]
ja, es ist aber ja noch nicht implementiert, den Endstand dann bitte aktualisieren.

**Comment by GvRecum** [comment]
Bitte auf Endstand anpassen.

**Comment by lmoedl** [comment]
erledigt. s. Doku
