### ISSUE TITLE
Querry- und Responseformat (normal und detail) ergründen

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/iOSX-App#2]
Wie fragen wir an?
Wie fragen wir Details an?
Wie reichern wir Ergebnisse mit Infos/Details an?

**Comment by pstoehr** [comment]
Die Antwort auf Frage 1 und 2 sind im EEXCEES zu finden (/recommend und /getDetails Anfrage an den Privacy-Proxy)

Frage 3 versteh ich nicht!

**Comment by GvRecum** [comment]
streiche Frage 3 setze:
alle möglichen "mediaTypes" & "licences" zusammentragen.
Schreibweise AE/BE license/licence & organization/organisation(type) mit Passau und ggf. @pstoehr abklären.
für die möglichen Lizenzen tabellarisch sinnvolle Abkürzungen entwickeln. (z.B. ccbyncsa)
bis heute **13:00 Uhr** abschliessen.

**Comment by lmoedl** [comment]
Welche Licenses und wofür sind die notwendig?

Gottfried von Recum notifications@github.com schrieb am Mi., 28. Okt.
2015 00:15:

**Comment by GvRecum** [comment]
Wie in der Dokumentation beschrieben enthält die Antwort "mediaTypes" und "licences".
Hierzu alle zu erwartenden Antworten ergründen.
vgl. https://github.com/EEXCESS/eexcess/wiki/%5B21.09.2015%5D-Request-and-Response-format#response-format

**Comment by lmoedl** [comment]
Erledigt. Beschreibung siehe Projektmaterial, Codeblock siehe MainController
