### ISSUE TITLE
Dokumentation der Constraints

### ISSUE THREAD

**Issue by bmairhoermann** [SECH-Tag-EEXCESS-Browser/iOSX-App#20]
@berol2 @philipp92

**Comment by ghost** [comment]
Die Dokumentation ist abgeschlossen. Habe da Stichpunkt artig was verfasst und ich häng das hier ran.
[Aufgaben Burak - Team Brian.pdf](https://github.com/SECH-Tag-EEXCESS-Browser/iOSX-App/files/68378/Aufgaben.Burak.-.Team.Brian.pdf)

**Comment by GvRecum** [comment]
Dokumentiert wird bitte in die LaTeXDokumentation, ich helfe auch gerne.

**Comment by ghost** [comment]
alles klar, chef

**Comment by GvRecum** [comment]
@bmairhoermann ist das dokumentiert?

**Comment by bmairhoermann** [comment]
Laut @berol2  schon.
Wenn noch nichts online ist dann öffne ich die issue nochmal
