### ISSUE TITLE
Testseiten auf sech-browser.de teilweise "merkwürdig"

### ISSUE THREAD

**Issue by pstoehr** [SECH-Tag-EEXCESS-Browser/iOSX-App#21]
Bei den Listen in den Webseiten test2, test3, ... ist der zweite Punkt in der Aufzählung leer weil die Einträge der ersten Zeile wohl fehlerhaft sind ...

**Comment by GvRecum** [comment]
betreffs "neue" Testseite:
Der search-head taucht schon mal im body auf, der gehört aber in den head
-> Testfall
Die komplette Seite ist in einem search-head tag
! Cave !
Und section und link heissen sech, statt search !
-> Testfälle
Der footer ist noch in der section
Vielleicht macht man das besser ausserhalb
Es sind außerdem die divs "Bierbraukunst" und "Verkehr" in der "Mobile Computing" section...

**Comment by apoehlmann** [comment]
die search-heads sind im head!

**Comment by apoehlmann** [comment]
```
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://avatars1.githubusercontent.com/u/15047100?v=3&s=200">

    <search-head topic="Bayreuth" type="location" mediaType="unknown" provider="ZBW" licence="unknown">

    <title>SechTest-Homepage der Hochschule Hof</title>

      <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Custom styles for this template -->
    <link href="style/mystyle.css" rel="stylesheet">
    <link href="style/carousel.css" rel="stylesheet">
  </head>

```

**Comment by GvRecum** [comment]
![bildschirmfoto 2015-12-19 um 10 49 24](https://cloud.githubusercontent.com/assets/11976678/11912477/5c755d64-a63e-11e5-9ea2-ef1d064a5d5f.png)

**Comment by apoehlmann** [comment]
Welche Seite?

**Comment by apoehlmann** [comment]
und ich hab einen Testfall ->

search-tags und links(<a>) kombiniert auf einer Seite

**Comment by GvRecum** [comment]
direkt auf der Startseite

Allerdings:
nur im Browser Vivaldi (Chromium)
Yandex ist ok (basiert auf Opera und Chromium)
Firefox ist ok
Safari ist ok

Ich denke mal für iOS Devices ist Safari ausschlaggebend.

**Comment by apoehlmann** [comment]
dann liegt es am Browser, wenn du den Html-Code anschaust(Brackets) ist alles ok

**Comment by GvRecum** [comment]
Ich sehe hier ja nur, was der Browser daraus macht.
Ich denke aber wenn es in Safari passt sind wir auf der sicheren Seite, und das tut es ja.

**Comment by apoehlmann** [comment]
und sind die search-tags auch insgesamt ok?

**Comment by GvRecum** [comment]
Die Section "EEXCESS" und der Link "Hochschule Hof" sind ok.
Die Section "Mobile Computing" und der Link "Smartphone" nicht (s.o.).
