### ISSUE TITLE
Projekte lassen sich nicht mehr öffnen

### ISSUE THREAD

**Issue by apoehlmann** [SECH-Tag-EEXCESS-Browser/iOSX-App#24]
Betroffen sind mindestens Sech Browser und Browser (Team UI).-> im master Branch

Fehlermeldung:
"Project /SECH Browser.xcodeproj cannot be opened because it is missing its project.pbxproj file"

und bei Browser (team UI):
"Project /Browser.xcodeproj cannot be opened because the project file cannot be parsed"

**Comment by pstoehr** [comment]
Nur keine Panik!
Die aktuelle Version ist jetzt im "best-ui" zu finden! 

"Master" ist tatsächlich mausetot, den sollte man "sperren", löschen oder ähnliches
![bildschirmfoto 2015-12-18 um 18 41 51](https://cloud.githubusercontent.com/assets/14542721/11903105/11446a60-a5b7-11e5-9fc4-875f7b46ad60.png)

**Comment by lmoedl** [comment]
Wie Herr Stöhr oben schon geschrieben hat, ist das aktuelle Projekt im best-ui Branch zu finden. Wenn das alte oder auch das neue Projekt nicht funktionieren sollte, liegt das an den Umlauten in den SEARCH-Tags. Das Problem hatten wir heute auch schon. Da muss @bmairhoermann nochmal nachbessern.

**Comment by GvRecum** [comment]
-> was passiert mit Seitenästen eines Hauptastes, wenn man den Hauptast löscht?

**Comment by pstoehr** [comment]
Vielleicht müssen wir über ein neues Repository nachdenken ...

Ich versuche auch rauszubekommen wie man in der Industrie die Probleme mit dem Storyboard und dem Project-Filw von Xcode in den Geiff bekommt ....

**Comment by apoehlmann** [comment]
wir können auch den best-ui auf Default-branch setzen und es vielleicht im Wiki vermerken oder im Readme

**Comment by GvRecum** [comment]
default branch ist -> best-ui
