### ISSUE TITLE
Search-Eintrag fehlt in der SECH-Liste

### ISSUE THREAD

**Issue by pstoehr** [SECH-Tag-EEXCESS-Browser/iOSX-App#26]
Bei der Demo-Seitenwird der im Text markierten SEARCH-Link nicht in die SECH-Tabelle übernommen (siehe Screenshot)
![bildschirmfoto 2016-01-14 um 14 59 37](https://cloud.githubusercontent.com/assets/14542721/12326195/8db6ca8e-bacf-11e5-8df0-b30cfbea5ed2.png)

**Comment by bmairhoermann** [comment]
Lag an den Special-Characters im tag
Habe die Regex angepasst.
Done
