### ISSUE TITLE
Extraction of SEARCH-Tag doesn't work correctly

### ISSUE THREAD

**Issue by pstoehr** [SECH-Tag-EEXCESS-Browser/iOSX-App#29]
Our test-page highlights "Auffanglager Moschendorf" but the SeCH-List shows only "Moschendorf"
![bildschirmfoto 2016-01-15 um 17 41 20](https://cloud.githubusercontent.com/assets/14542721/12358786/349c954c-bbaf-11e5-9d5a-5c5963e86f4e.png)

**Comment by bmairhoermann** [comment]
This was caused by special-character in sech-tag
I fixed the Regex.
Done.

**Comment by pstoehr** [comment]
Fixed for "Moschendorf" but still open vor "Bahnhof Hof-Neuhof"

![bildschirmfoto 2016-01-16 um 16 57 51](https://cloud.githubusercontent.com/assets/14542721/12373222/70d7275c-bc72-11e5-8ed0-96928fe29477.png)

But it works for Fachakademie ...
![bildschirmfoto 2016-01-16 um 17 02 22](https://cloud.githubusercontent.com/assets/14542721/12373234/1240e038-bc73-11e5-813f-90551fccd924.png)

**Comment by bmairhoermann** [comment]
Actually, the Sidebar displays the _topic_ of the tag, not the innerHTML of the tag.

**Comment by pstoehr** [comment]
Sorry, my fault!

**Comment by pstoehr** [comment]
But even after changing the Search-Tag to
<search-link topic="Bahnhof Hof-Neuhof" type="misc" mediaType="text" provider="Europeana" licence="unknown">
only "Hof-Neuhof" is displayed in the list ...

I guess, the syntax is correct!

![bildschirmfoto 2016-01-16 um 17 23 57](https://cloud.githubusercontent.com/assets/14542721/12373321/f4ad08f0-bc75-11e5-874f-f3b4a107e234.png)
![bildschirmfoto 2016-01-16 um 17 23 40](https://cloud.githubusercontent.com/assets/14542721/12373322/f8f6a664-bc75-11e5-9b08-277d7cfcd5bd.png)

**Comment by bmairhoermann** [comment]
I have tested the regex externally and got a positiv result. At the moment i have no idea where this bug could come from.

**Comment by bmairhoermann** [comment]
Well it works fine for me:

![bildschirmfoto 2016-01-16 um 18 06 45](https://cloud.githubusercontent.com/assets/11869474/12373525/06ff485a-bc7c-11e5-8b87-b48509645095.png)
![bildschirmfoto 2016-01-16 um 18 06 58](https://cloud.githubusercontent.com/assets/11869474/12373532/0f9e033e-bc7c-11e5-8217-dba4459610f8.png)

**Comment by pstoehr** [comment]
After removing the app from the simulator and starting the app new it works for me too.
