### ISSUE TITLE
JSON Prototyp erstellen für die Anfrage (Recommendation-Anfrage)

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/iOSX-App#3]

**Comment by apoehlmann** [comment]
Mit dem Prototype ist es jetzt möglich komplexere Anfragen zuerstellen.

**Comment by GvRecum** [comment]
Kommatrennung in Recommendation/Response-DropDown beachten (Leerzeichen eingefügt)
type "organization" einfügen
bis heute **13:00 Uhr** abschliessen

**Comment by apoehlmann** [comment]
Wir haben die Anfrage erweitert und Auswahlmöglichkeiten sind auch möglich

**Comment by apoehlmann** [comment]
PP-QF2 Format wird jetzt unterstützt
