### ISSUE TITLE
Selecting "Moschendorf" in our test-document leads to a crash

### ISSUE THREAD

**Issue by pstoehr** [SECH-Tag-EEXCESS-Browser/iOSX-App#30]
![bildschirmfoto 2016-01-15 um 17 41 59](https://cloud.githubusercontent.com/assets/14542721/12358812/5b82bc4a-bbaf-11e5-86e8-c7f32bd73f8f.png)

**Comment by bmairhoermann** [comment]
On which page is this tag?
What test-document do you mean?

**Comment by pstoehr** [comment]
Steps to reproduce:
1) Click "Home"
2) Select "Stadt Hof"  in the drop-down menue at the right 
3) Select "Geschichte"
4) Open table with Sech-Links
5) Click on "Moschendorf"

Unfortunately the crash only occurs on 1 out of 10 times ...

For more information a hardcopy is attached ...
![bildschirmfoto 2016-01-16 um 16 34 54](https://cloud.githubusercontent.com/assets/14542721/12373116/2c9434ac-bc6f-11e5-8644-6b9096190b9a.png)

**Comment by lmoedl** [comment]
This problem occurs every time even if the server doesn't deliver any results for the selected tag. I can't reproduce this fault now, but i should be solved now.
