### ISSUE TITLE
Preferences in den Prototype integrieren

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/iOSX-App#4]
Was wollen wir für Einstellungsmöglichkeiten geben?
Wie soll das geschehen?

**Comment by tpohrer** [comment]
Erledigt!
[Einstellungsmöglichkeiten.pdf](https://github.com/SECH-Tag-EEXCESS-Browser/iOSX-App/files/20162/Einstellungsmoglichkeiten.pdf)

Wie der Nutzer die Daten eingibt, also wie der Einstellungsscreen aussieht ist nicht unsere Aufgabe.

**Comment by pstoehr** [comment]
Kann man das ganze bitte mit der Dokumentation und den Möglichkeiten des Privacy-Proxies abgleichen?
So unterstützt der PP zum Beispiel nur einen "ageRange", und den auch nicht wirklich, denn bei der Parameterübergabe stürzt das System aktuell ab :(
Siehe auch: https://github.com/EEXCESS/eexcess/issues/11

**Comment by chseifert** [comment]
Soll diese Woche (hoffentlich heute) behoben sein.

**Comment by GvRecum** [comment]
mit @apoehlmann bis **Fr. 30.10.15** in die Anfrage integrieren

**Comment by GvRecum** [comment]
PDF bitte in Projektmaterial ablegen.

**Comment by tpohrer** [comment]
Preferences wurden in den Prototyp integriert. 
Kommen aber teilweise Antworten zurück, die nicht mit den Preferences übereinstimmen bzw. manchmal beeinflussen die Preferences die Antworten nicht.

**Comment by pstoehr** [comment]
Wenn die Funktionalität nicht fehlerfrei implementiert ist, wieso wird dann der Issue geschlossen?

**Comment by GvRecum** [comment]
siehe #12
