### ISSUE TITLE
SECH Tags definieren

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/iOSX-App#5]
Was beinhalten die SECH Tags?
Wie sind sie strukturiert?

**Comment by GvRecum** [comment]
https://github.com/SECH-Tag-EEXCESS-Browser/Documentation/wiki/SECH-Tag

**Comment by pstoehr** [comment]
Die Endversion der Dokumentation kommt bitte ins LaTeX-File!

**Comment by GvRecum** [comment]
-> auf search anpassen

**Comment by bmairhoermann** [comment]
Anpassung auf search geschehen

**Comment by GvRecum** [comment]
doku durchgehend anpassen

**Comment by GvRecum** [comment]
Bitte überprüfen, ob die Doku so stimmt.

**Comment by GvRecum** [comment]
selbst überprüft.
