### ISSUE TITLE
ViewController der SECH-Demo-App lässt sich nicht übersetzen

### ISSUE THREAD

**Issue by pstoehr** [SECH-Tag-EEXCESS-Browser/iOSX-App#6]
Hi,

ich bekomme in Zeile 72 der Datei ViewController die Fehlermeldung, dass der Aufruf der setKeyWords nicht passt.

**Comment by apoehlmann** [comment]
Ich hatte vergessen die Zeile auszukommentieren vor dem Push, aber Ich hab auf dem lokalem Repro schon eine neue Version

**Comment by apoehlmann** [comment]
Prototype funktioniert wieder komplett. Das Dropdown oben rechts im UI muss beim nächsten Push noch entfernt werden.
