### ISSUE TITLE
Detailanfragen realisieren

### ISSUE THREAD

**Issue by GvRecum** [SECH-Tag-EEXCESS-Browser/iOSX-App#7]
im Prototyp, zu ausgewählten Responses, Details anfragen können.
User Preferences mit @tpohrer integrieren.
bis **Fr. 30.10.15** realisieren.

**Comment by apoehlmann** [comment]
issue #4

**Comment by GvRecum** [comment]
Detailanfragen legen wir erstmal ad acta
