### ISSUE TITLE
Implementierung der Grundfunktionalitäten des Browsers

### ISSUE THREAD

**Issue by bmairhoermann** [SECH-Tag-EEXCESS-Browser/iOSX-App#9]
Lesezeichen, Adressleiste (mit Suchoption), Homebutton, Preferences

Bei Implementierung bitte auch gleich die Dokumentation dazu füllen.
Wer sich einer der Sachen annimmt, schreibt bitte einen kurzen Kommentar drunter.

**Comment by pbuettner90** [comment]
ich mach dann die lesezeichen

**Comment by drui** [comment]
Hab mal n bisschen was an der Adressleiste gemacht. 
Suche funktioniert. 
"HTTP(S)://" einfügen muss noch überarbeitet werden.
Aktuelle URL anzeigen fehlt noch.

**Comment by drui** [comment]
Adressleiste fertig.

**Comment by drui** [comment]
@pbuettner90 Funktionen die bei den Lesezeichen noch fehlen:
- beim antippen laden
- persistent speichern
- einzelne Lesezeichen löschen

Weiß nicht ob du das noch geplant hattest, aber mir is es vorhin aufgefallen.

**Comment by bmairhoermann** [comment]
Alles erledigt
